tasks:
  installDeps:
    name: Install dependencies
    description: Download the project's Clojure dependencies.
    command: |
      clojure -P
      clojure -P -M:run
    triggeredBy:
      - manual
      - postDevcontainerStart
      - prebuild

services:
  kit-server:
    name: Kit Server
    description: Run the Kit/Undertow web server.
    triggeredBy:
      - manual
      - postEnvironmentStart
    commands:
      start: |
        ona environment port open 3000 --dont-wait --admission creator_only --name "Kit Server"
        clojure -M:run
      ready: |
        curl -sf http://localhost:3000/healthz
